FROM alpine AS spire-base
ARG ARCH
ARG OS
WORKDIR /opt/spire
RUN apk --no-cache --update add build-base git mercurial
RUN apk --no-cache --update add dumb-init
RUN apk --no-cache --update add ca-certificates
RUN mkdir -p /opt/spire/bin
CMD []

# K8S Workload Registrar
FROM spire-base AS k8s-workload-registrar
COPY output/bin/${OS}/${ARCH}/k8s-workload-registrar bin/k8s-workload-registrar
ENTRYPOINT ["/usr/bin/dumb-init", "/opt/spire/bin/k8s-workload-registrar"]
